#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d term web code file music 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a kitty desktop='^1'
bspc rule -a firefox desktop='^2'

feh --bg-scale $HOME/.config/wallpapers/wallpaper.jpg &
picom &
bash $HOME/.config/polybar/docky/launch.sh &
setxkbmap at
